# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jr. Developer
email: jcrockyeis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Computer Science Engineer that loves to learn new stuff about code, passion for music, movies and videogames and esports. Looking to share thought about differents subjects and meet new people that's willing to chat about it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Yeis
github_username:  Yeis

# Build settings
markdown: kramdown
